spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/select_eazy?createDatabaseIfNotExist=true&useTimezone=true&serverTimezone=UTC
    username: postgres
    password: adm123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true